name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '[15.9,15.10)'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet packages
        run: nuget restore src/TcBlack.sln

      - name: Create certificates
        run: |
         Set-Content -Path src/TcBlackCLI/TcBlackCLI_certificate.txt -Value '${{ secrets.TCBLACKCLI_CERTIFICATE }}'
         certutil -decode src/TcBlackCLI/TcBlackCLI_certificate.txt src/TcBlackCLI/TcBlackCLI.pfx
         Set-Content -Path src/TcBlackCore/TcBlackCore_certificate.txt -Value '${{ secrets.TCBLACKCORE_CERTIFICATE }}'
         certutil -decode src/TcBlackCore/TcBlackCore_certificate.txt src/TcBlackCore/TcBlackCore.pfx

      - name: Build the solution
        run: msbuild src/TcBlack.sln /m
        
      - name: Run Tests
        run: vstest.console.exe src\TcBlackCLITests\bin\Debug\TcBlackCLITests.dll src\TcBlackCoreTests\bin\Debug\TcBlackCoreTests.dll
      
